config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Пользователь
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/show_subs", to: "users#show_subs", as: :user_show_subs


  get "up" => "rails/health#show", as: :rails_health_check

  # Посты
  get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  patch "/blog_posts/:id", to: "blog_posts#update"
  delete "/blog_posts/:id", to: "blog_posts#destroy"
  get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  # Лайки
  resources :blog_posts do
    resources :likes, only: [ :create, :destroy ]
  end

  # Подписки
  post "/subscribe/:id", to: "subscriptions#create", as: :subscribe
  delete "/subscribe/:id", to: "subscriptions#destroy", as: :unsubscribe

  # post "/blog_posts/:id/likes", to: "likes#create"
  # delete "/blog_posts/:id/likes/:id", to: "likes#destroy"

  # API маршруты
  Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      # Маршруты для постов
      get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
      get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
      patch "/blog_posts/:id", to: "blog_posts#update"
      delete "/blog_posts/:id", to: "blog_posts#destroy"
      get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
      post "/blog_posts", to: "blog_posts#create", as: :blog_posts

      # Маршруты для лайков
      resources :blog_posts do
        resources :likes, only: [ :create, :destroy ]
      end

      # Маршруты для пользователей
      get "/users/:id", to: "users#show", as: "user"
      get "/users/:id/show_subs", to: "users#show_subs", as: :user_show_subs

      # Маршрут для подписок
      post "/subscribe/:id", to: "subscriptions#create", as: :subscribe
      delete "/subscribe/:id", to: "subscriptions#destroy", as: :unsubscribe

      # Маршруты для сессий (авторизация)
      # post "login", to: "sessions#create"
      # delete "logout", to: "sessions#destroy"
    end
  end
end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :image, presence: { message: "в посте должна быть обязательно" }
end

app/controllers/api/v1/blog_posts_controller.rb
class Api::V1::BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [ :new, :update, :destroy ]
  before_action :authenticate_user, except: [ :index, :show ]
  before_action :authorize_user, only: [ :edit, :update, :destroy ]
  def index
    # @blog_posts = BlogPost.all
    @title = "Мой Блог"

    if params[:search].present?
      @blog_posts = BlogPost.where("title LIKE ?", "%#{params[:search]}%")
      @search_term = params[:search]
      @no_results = @blog_posts.empty?

      render json: @blog_posts
    else
      @blog_posts = BlogPost.all
      @search_term = nil
      @no_results = false

      render json: @blog_posts
    end
  end

  def show
    render json: @blog_post
  end

  def new
    @blog_post = current_user.blog_posts.build

    render json: @blog_post
  end

  def create
    @blog_post = current_user.blog_posts.build(blog_post_params)
    if @blog_post.save
      render json: @blog_post, status: :created
      redirect_to @blog_post
    else
      render json: @blog_post.errors, status: :unprocessable_entity
    end
  end

  def edit
    render json: @blog_post
  end

  def update
    if @blog_post.update(blog_post_params)
      render json: @blog_post
      redirect_to @blog_post, notice: "Пост успешно изменён"
    else
      render json: @blog_post.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :image)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authorize_user
    unless @blog_post.user == current_user
      redirect_to root_path, alert: "У вас нет доступа, чтобы выполнить это действите"
    end
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [ :new, :update, :destroy ]
  before_action :authorize_user, only: [ :edit, :update, :destroy ]
  def index
    # @blog_posts = BlogPost.all
    @title = "Мой Блог"

    if params[:search].present?
      @blog_posts = BlogPost.where("title LIKE ?", "%#{params[:search]}%")
      @search_term = params[:search]
      @no_results = @blog_posts.empty?
    else
      @blog_posts = BlogPost.all
      @search_term = nil
      @no_results = false
    end
  end

  def show
  end

  def new
    @blog_post = current_user.blog_posts.build
  end

  def create
    @blog_post = current_user.blog_posts.build(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: "Пост успешно изменён"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :image)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authorize_user
    unless @blog_post.user == current_user
      redirect_to root_path, alert: "У вас нет доступа, чтобы выполнить это действите"
    end
  end
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
        <div class="errors_wrapper">
            <h2 class="errors_wrapper-title">Не удалось опубликовать пост</h2>
            <% form.object.errors.full_messages.each do |message| %>
                <li class="errors_wrapper-subtitle" style="list-style: none"><%= message %></li>
            <% end %>
        </div>
    <% end %>

    <div class="field">
        <h3>Заголовок <span style="color: red;">*</span> </h3>
        <!--<%= form.label "Заголовок" %>-->
        <%= form.text_field :title %>
    </div>
    
    <div class="field">
        <h3>Текст поста <span style="color: red;">*</span> </h3>
        <!--<%= form.label "Текст поста" %>-->
        <%= form.text_area :content %>
    </div>

    <div class="field">
        <%= form.label "Выбрать картинку для поста", class: "upload_file_button", for: "blog_post_image" %>
        <%= form.file_field :image %>
    </div>
    
    <div class="button_wrapper">
        <%= form.button "Опубликовать", class: "submit_button" %>
    </div>
    
<% end %>

app/views/blog_posts/edit.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Фото-блог</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>

    <header class="header">
        <div class="header-top">
            <%= link_to "ФОТО БЛОГ", root_path, class: "logo" %>

            <nav class="navigation">
                <ul class="menu">
                    <li class="menu-element">
                        <i style="color: #000;" class="fa-solid fa-house"></i>
                        <%= link_to "Главная", root_path %>
                    </li>
                    
                    <li class="menu-element">
                        <% if user_signed_in? %>
                            <i style="color: #000;" class="fa-solid fa-user"></i>
                            <%= link_to "Мой профиль", user_path(current_user) %>
                        <% end %>
                    </li>

                    <li class="menu-element">
                        <% if user_signed_in? %>
                            <% if current_user.avatar.attached? %>
                                <img style="width: 50px; height: 50px; border-radius: 100px;" <%= image_tag url_for(current_user.avatar) %> />
                            <% else %>
                                <%= image_tag "base-avatar.jpg", style: "width: 50px; height: 50px; border-radius: 100px;" %>
                            <% end %>
                        <% end %>
                    </li>

                    <% if !user_signed_in? %>
                        <li class="menu-element">
                            <%= link_to "Войти", new_user_session_path %>
                        </li>

                        <li class="menu-element">
                            <%= link_to "Регистрация", new_user_registration_path %>
                        </li>
                    <% end %>

                    
                    <%= form_tag root_path, method: :get do %>
                        <%= text_field_tag :search, params[:search], placeholder: "Найти пост", class: "search_field" %>
                        <%= submit_tag "Поиск", class: "search_button" %>
                    <% end %>
                    </li>
                </ul>
            </nav>

            
            
        </div>
    </header>



    <h1 style="text-align: center; font-size: 30px;">Изменения поста</h1>

    <%= render partial: "form", locals: {blog_post: @blog_post} %>

    <hr style="max-width: 550px; margin: 25px auto; border: 0.5px solid #a9a9a9ff;">
    <div class="button_wrapper">
        <%= button_to "Удалить пост", @blog_post, method: :delete, data: {turbo_confirm: "Вы уверены, что хотите удалить пост?"}, class: "delete_button"%>
    </div>

    <script src="https://kit.fontawesome.com/c6ba37b0b2.js" crossorigin="anonymous"></script>
        
</body>
</html>

 

app/views/blog_posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>

    <header class="header">
        <div class="header-top">
            <%= link_to "ФОТО БЛОГ", root_path, class: "logo" %>

            <nav class="navigation">
                <ul class="menu">
                    <li class="menu-element">
                        <i style="color: #000;" class="fa-solid fa-house"></i>
                        <%= link_to "Главная", root_path %>
                    </li>

                    <li class="menu-element">
                        <i style="color: #000;" class="fa-solid fa-plus"></i>
                        <%= link_to "Добавить пост", "/blog_posts/new" %>
                    </li>

                    <li class="menu-element">
                        <% if user_signed_in? %>
                            <i style="color: #000;" class="fa-solid fa-user"></i>
                            <%= link_to "Мой профиль", user_path(current_user) %>
                        <% end %>
                    </li>

                    <li class="menu-element">
                        <% if user_signed_in? %>
                            <% if current_user.avatar.attached? %>
                                <img style="width: 50px; height: 50px; border-radius: 100px;" <%= image_tag url_for(current_user.avatar) %> />
                            <% else %>
                                <%= image_tag "base-avatar.jpg", style: "width: 50px; height: 50px; border-radius: 100px;" %>
                            <% end %>
                        <% end %>
                    </li>

                    <% if !user_signed_in? %>
                        <li class="menu-element">
                            <%= link_to "Войти", new_user_session_path %>
                        </li>

                        <li class="menu-element">
                            <%= link_to "Регистрация", new_user_registration_path %>
                        </li>
                    <% end %>

                    
                    <%= form_tag root_path, method: :get do %>
                        <%= text_field_tag :search, params[:search], placeholder: "Найти пост", class: "search_field" %>
                        <%= submit_tag "Поиск", class: "search_button" %>
                    <% end %>
                    </li>
                </ul>
            </nav>

            
            
        </div>
    </header>

    <section>
        <div align="center">
            <h1 class="blog_title">ЛЕНТА ПОСТОВ</h1>
        </div>
    </section>


    <section>
        <div class="container">
            <div class="wrapper">
                <% if @no_results %>
                    <h3 class="no_result_search">Посты не найдены</h3>
                <% else %>
                    <% @blog_posts.each do |blog_post| %>
                        <div align="center" class="wrapper_post">
                            
                            <% if blog_post.user.avatar.attached? %>
                                <img class="user_avatar" <%= image_tag url_for(blog_post.user.avatar) %>
                            <% else %>
                                <%= image_tag "base-avatar.jpg", style: "width: 75px; height: 75px; border-radius: 100px; margin-top: 25px;" %>
                            <% end %>

                            <% if @search_term.present? %>
                                <h2>
                                <%= highlight(blog_post.title, @search_term, highlighter: '<span class="highlight">\1</span>') %>
                                </h2>
                            <% else %>
                                <h2><%= blog_post.title %></h2>
                            <% end %>
                            
                            <!--<h2 class="blog_post_title"> <%= blog_post.title%> </h2>-->

                            <hr>
                            <img style="width: 500px; height: 500px; border-radius: 12px;" <%= image_tag blog_post.image %>
                            <h4 class="post_date"><%= blog_post.created_at&.in_time_zone&.strftime("%Y-%m-%d %H:%M") %> <br> </h4>

                            <p><i class="fa-solid fa-thumbs-up"></i> <%= blog_post.likes.count %></p>
                            
                            <!-- blog_post.likes.exists? -->
                            <% if user_signed_in? %>
                                <% if current_user.likes.exists?(blog_post: blog_post) %>
                                    <% like = current_user.likes.find_by(blog_post: blog_post) %>
                                    <!-- blog_post.likes.first -->
                                    <%= button_to 'Не нравится', blog_post_like_path(blog_post, like), method: :delete, remote: true, class: "like_button" %>
                                <% else %>
                                    <%= button_to "Нравится", blog_post_likes_path(blog_post), method: :post, remote: true, data: { turbo_stream: true }, class: "like_button" %>
                                <% end %>
                            <% end %>
                            

                            <%= link_to "Читать", blog_post, class: "index_link_to_post" %>
                        </div>
                        <br>
                    <% end %>
                <% end %>
                
            </div>
        </div>
    </section>


    <script src="https://kit.fontawesome.com/c6ba37b0b2.js" crossorigin="anonymous"></script>
    
</body>
</html>

app/views/blog_posts/new.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Фото-блог</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>

    <header class="header">
        <div class="header-top">
            <%= link_to "ФОТО БЛОГ", root_path, class: "logo" %>

            <nav class="navigation">
                <ul class="menu">
                    <li class="menu-element">
                        <i style="color: #000;" class="fa-solid fa-house"></i>
                        <%= link_to "Главная", root_path %>
                    </li>

                    <li class="menu-element">
                        <% if user_signed_in? %>
                            <i style="color: #000;" class="fa-solid fa-user"></i>
                            <%= link_to "Мой профиль", user_path(current_user) %>
                        <% end %>
                    </li>

                    <li class="menu-element">
                        <% if user_signed_in? %>
                            <% if current_user.avatar.attached? %>
                                <img style="width: 50px; height: 50px; border-radius: 100px;" <%= image_tag url_for(current_user.avatar) %> />
                            <% else %>
                                <%= image_tag "base-avatar.jpg", style: "width: 50px; height: 50px; border-radius: 100px;" %>
                            <% end %>
                        <% end %>
                    </li>

                    <% if !user_signed_in? %>
                        <li class="menu-element">
                            <%= link_to "Войти", new_user_session_path %>
                        </li>

                        <li class="menu-element">
                            <%= link_to "Регистрация", new_user_registration_path %>
                        </li>
                    <% end %>

                    
                    <%= form_tag root_path, method: :get do %>
                        <%= text_field_tag :search, params[:search], placeholder: "Найти пост", class: "search_field" %>
                        <%= submit_tag "Поиск", class: "search_button" %>
                    <% end %>
                    </li>
                </ul>
            </nav>

            
            
        </div>
    </header>
    
    <h1 style="text-align: center;">Новый пост в блоге</h1>

    <%= render partial: "form", locals: {blog_post: @blog_post} %>


    <script src="https://kit.fontawesome.com/c6ba37b0b2.js" crossorigin="anonymous"></script>
    
</body>
</html>

app/views/blog_posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyBlog</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>

<body>

    <header class="header">
        <div class="header-top">
            <%= link_to "ФОТО БЛОГ", root_path, class: "logo" %>

            <nav class="navigation">
                <ul class="menu">
                    <li class="menu-element">
                        <i style="color: #000;" class="fa-solid fa-house"></i>
                        <%= link_to "Главная", root_path %>
                    </li>

                    <% if user_signed_in? %>
                        <li class="menu-element">
                            <%= link_to "Мой профиль", user_path(current_user) %>
                        </li>
                    <% end %>

                    <% if !user_signed_in? %>
                        <li class="menu-element">
                            <%= link_to "Войти", new_user_session_path%>
                        </li>
                        
                        <li class="menu-element">
                            <%= link_to "Регистрация", new_user_registration_path%>
                        </li>
                    <% end %>
                    
                </ul>
            </nav>

            
            
        </div>
    </header>

    <h1 align="center" style="font-size: 19px;">Автор поста: <%= @blog_post.user.username %></h1>
    <% if @blog_post.user.avatar.attached? %>
        <img style="width: 160px; height: 160px; border-radius: 100px; display: block; margin: 0 auto;" <%= image_tag url_for(@blog_post.user.avatar) %>
    <% else %>
        <%= image_tag "base-avatar.jpg", style: "width: 160px; height: 160px; border-radius: 100px; display: block; margin: 0 auto;" %>
    <% end %>

    <% if user_signed_in? && current_user != @blog_post.user %>
        <% if current_user.subscribed_users.include?(@blog_post.user) %>
            <% subscription = current_user.subscriptions.find_by(subscribed_to_id: @blog_post.user.id) %>
            <%= button_to "Отписаться от #{@blog_post.user.username}", unsubscribe_path(subscription), method: :delete, class: "subs_button" %>
        <% else %>
            <%= button_to "Подписаться на #{@blog_post.user.username}", subscribe_path(subscription: { subscribed_to_id: @blog_post.user.id }), method: :post, class: "subs_button" %>
        <% end %>
    <% end %>
    
    <div align="center">
        <h1><%= @blog_post.title %></h1>
        <% if @blog_post.image.attached? %>
            <img style="width: 750px; height: 600px;" <%= image_tag url_for(@blog_post.image) %>
        <% end %>
        <div class="wrapper_text">
            <p><%= @blog_post.content %></p>
        </div>
    </div>


    <% if user_signed_in? && @blog_post.user == current_user %>
        <h1 align="center" style="font-size: 19px;"><%= link_to "Изменить пост", "/blog_posts/#{@blog_post.id}/edit", class: "edit_post" %></h1>
    <% end %>

    <script src="https://kit.fontawesome.com/c6ba37b0b2.js" crossorigin="anonymous"></script>

</body>